export default [
  {
    bookImmediately: true,
    cuisines: ['Korean', 'Mexican', 'Fusion'],
    id: 1,
    name: 'Chi’lantro BBQ',
    priceRange: '$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.chilantrobbq.com',
  },
  {
    bookImmediately: false,
    cuisines: ['BBQ', 'Tex-Mex'],
    id: 2,
    name: 'Valentina’s Tex Mex BBQ',
    priceRange: '$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.valentinastexmexbbq.com',
  },
    {
    bookImmediately: true,
    cuisines: ['Vegan', 'Vegetarian', 'American'],
    id: 3,
    name: 'Arlo’s',
    priceRange: '$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.arlostruck.com',
  },
  {
    bookImmediately: false,
    cuisines: ['Cajun'],
    id: 4,
    name: 'Baton Creole',
    priceRange: '$$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.batoncreole.com',
  },  {
    bookImmediately: true,
    cuisines: ['Tex-Mex', 'Mexican', 'Dessert'],
    id: 5,
    name: 'Churro Co.',
    priceRange: '$$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.churrocoaustin.com',
  },
  {
    bookImmediately: false,
    cuisines: ['Asian', 'Thai'],
    id: 6,
    name: 'Dee Dee',
    priceRange: '$$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.deedeeatx.com',
  },  {
    bookImmediately: true,
    cuisines: ['Asian', 'Thai'],
    id: 7,
    name: 'Thai-Kun',
    priceRange: '$$$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.thaikun.com',
  },
  {
    bookImmediately: false,
    cuisines: ['Tex-Mex'],
    id: 8,
    name: 'El Primo',
    priceRange: '$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.elprimomex.com/ElPrimo/Texas/Austin.aspx',
  },  {
    bookImmediately: true,
    cuisines: ['Seafood', 'American'],
    id: 9,
    name: 'Garbo’s Lobster Truck',
    priceRange: '$$$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.garboslobsteratx.com',
  },
  {
    bookImmediately: false,
    cuisines: ['Mediterranean'],
    id: 10,
    name: 'Kebabalicious',
    priceRange: '$',
    thumbnail: 'http://placehold.it/200x200',
    website: 'www.kebabalicious.com',
  },
];